# Generated by Django 5.2.13 on 2026-08-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='is_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='match_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
